site_name: BOTL Farm
site_url: http://projects.botlfarm.com
repo_url: https://github.com/botlfarm/Farm_projects_Website
edit_uri: edit/main/docs/
copyright: <p><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>


nav:
    - Home: index.md
    - Shelters: shelters
    
markdown_extensions:
  - toc:
      permalink: true
